### ISSUE TITLE
could you please provide a more detailed how to use this module

### ISSUE THREAD

**Issue by jasonmckelvin** [itigoag/ansible.packages#2]
Hello, 

i am an Ansible novice and i am struggling to understand how to use your module. It looks great but i have not the slightest idea how to use. F.e. i want to install 7zip, firefox, chrome and so on but no idea where to put the information in.

thank you in advance

**Comment by sbaerlocher** [comment]
Hello jasonmckelvin

Have you already set up a working Ansible environment with a connection to a device?

**Comment by jasonmckelvin** [comment]
Hello

Yes I have something prepared which works well (very easy and simple playbook and roles) 
I am using dochang, gantsign and geerlingguy roles with a very simple playbook.

Cheers

**Comment by sbaerlocher** [comment]
@jasonmckelvin did you get any further?

If there is no further message I will close the issues in 2 days.

**Comment by jasonmckelvin** [comment]
Pleas close

Ches
